
pipeline {
    agent none
    stages {
        stage('Back-end') {
            agent {
                label 'maven'
            }
            steps {
                script {
                    docker.image('maven:3.8.1-adoptopenjdk-11').inside {
                        sh 'mvn --version'
                    }
                }
            }
        }
        stage('Front-end') {
            agent {
                label 'node'
            }
            steps {
                script {
                    docker.image('node:16-alpine').inside {
                        sh 'node --version'
                    }
                }
            }
        }
    }
}

